<?php
/**
 * @author XJ.
 * @Date   2024/9/2 星期一
 */

namespace Fatbit\FormRequestParam\Abstracts;

use Hyperf\Database\Model\Model;

interface ParamModelMappingInterface
{

    /**
     * 转换成模型
     *
     * @author XJ.
     * @Date   2024/9/2 星期一
     * @template T
     *
     * @param string|class-string<T> $modelName
     *
     * @return object|null|T|Model
     */
    public function toModel(string $modelName): ?object;

    /**
     * 转换成模型数组
     * 用于数组参数批量转换
     *
     * @author XJ.
     * @Date   2024/9/2 星期一
     * @template T
     *
     * @param string|class-string<T> $modelName
     *
     * @param callable|null          $call
     *
     * @return array|T[]|Model[]
     */
    public function toModels(string $modelName, ?callable $call = null): array;
}